apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -medium

resources:
- ../base

commonLabels:
  app: pmbench-medium

configMapGenerator:
- name: pmbench
  behavior: merge
  literals:
    - extra='--setsize 20000 --mapsize 40000 2000000 --initialize -a touch -j 8'

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: generator
            resources:
              requests:
                cpu: 16
                memory: 45G
              limits:
                cpu: 16
                memory: 45G
