apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -big-wss

resources:
- ../base

commonLabels:
  app: pmbench-big-wss

configMapGenerator:
- name: pmbench
  behavior: merge
  literals:
    - extra='--setsize 80000 --mapsize 80000 2000000 --initialize -a touch -j 4'

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: generator
            resources:
              requests:
                cpu: 8
                memory: 90G
              limits:
                cpu: 8
                memory: 90G
